export enum RouteName {
  Landing = 'landing',
  Contact = 'contact',
  Resume = 'resume',
  Visuals = 'visuals',
  VisualsIndex = 'visuals-index',
  VisualsFlexGrid = 'visuals-flex-grid',
  VisualsJs = 'visuals-js',
  VisualsAnimation = 'visuals-animation',
  Notes = 'notes',
  Tutoring = 'tutoring',
  Ai = 'ai',
  Demo = 'demo',
  NotFound = 'not-found',
}