export enum RouteName {
  Landing = 'landing',
  Contact = 'contact',
  Resume = 'resume',
  Visuals = 'visuals',
  VisualsIndex = 'visuals-index',
  VisualsFlexGrid = 'visuals-flex-grid',
  VisualsJs = 'visuals-js',
  VisualsAnimation = 'visuals-animation',
  VisualsBase64 = 'visuals-base64',
  Notes = 'notes',
  Tutoring = 'tutoring',
  Teaching = 'teaching',
  TeachingIndex = 'teaching-index',
  TeachingToeic = 'teaching-toeic',
  TeachingDetail = 'teaching-detail',
  Ai = 'ai',
  Demo = 'demo',
  NotFound = 'not-found',
}